language: rust
rust: stable
dist: xenial

before_script:
  - rustc -V
  - cargo -V
  - git --version
  - git rev-parse HEAD

install:
  - bash ci/install.sh

script:
  - mdbook build
  - mdbook test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: book
  keep-history: false
  fqdn: os.neet.club
  on:
    branch: master

cache: cargo

notifications:
  email:
    on_success: never
